version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mg_vol:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 30133:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  node:
    container_name: node
    build: ./
    restart: always
    environment:
      DB: MONGO
      MONGO_URL: mongodb://root:example@mongo:27017/
      BASE_HOST: http://localhost
      BASE_PATH: /node
    networks:
      - dc-net

networks:
  dc-net:
    external: true

volumes:
  mg_vol: